--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AyzrixYTB/SimpleFaction
branches:
  - master
projects:
  SimpleFaction:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.3.1
...
