---
#--------------------------------------------------
#SETTINGS CONFIGURATION
#--------------------------------------------------

# SQLITE | MYSQL
PROVIDER: "SQLITE"

mysql_address: "SERVER ADDRESS"
mysql_user: "USER"
mysql_password: "YOUR PASSWORD"
mysql_db: "YOUR DB"

broadcast_message_created: true
broadcast_message_disband: true

min_faction_name_lenght: 3
max_faction_name_lenght: 16

power_gain_per_kill: 1
power_lost_per_death: 1

faction_worlds: ["world"]

# TRUE = ENABLE | FALSE = DISABLE
faction_pvp: false
alliance_pvp: false

# expire in seconds
invitation_expire_time: 30
allies_invitation_expire_time: 60

faction_max_members: 20
faction_max_allies: 2

# USAGE: "- POWER NEEDED"
claims:
  - 100
  - 500
  - 800
  - 1000
  - 2500
  - 5000

#--------------------------------------------------
# LANGUAGE CONFIGURATION
#--------------------------------------------------
PREFIX: "§6[§fSimpleFaction§6]§f"
PLAYER_ONLY: "{prefix} §cThis command can't be used in the console !"
COMMAND_USAGE: "{prefix} §cThis command does not exist. Use /f help for more command informations !"
HELP_HEADER: "§6- §fFaction help page §6(§f%§6/§f%§6) §6-"
HELP_1: "§6- §f/f create (name) §6- §fCreate a faction.\n§6- §f/f del §6- §fDelete your faction.\n§6- §f/f info §6- §fGet information on a faction.\n§6- §f/f sethome §6- §fSets your faction home.\n§6- §f/f delhome §6- §fDestroys your faction's house."
HELP_2: "§6- §f/f home §6- §fQuick way to get to your faction's home.\n§6- §f/f (claim|unclaim) §6- §fClaim or unclaim your base.\n§6- §f/f (promote|demote) (player) §6- §fPromote or demote a player.\n§6- §f/f leave §6- §fLeave your current faction.\n§6- §f/f kick (player) §6- §fKicks a player from your faction."
HELP_3: "§6- §f/f invite (player) §6- §fInvite a player into your faction.\n§6- §f/f (accept|deny) §6- §fAccept or deny any faction.\n§6- §f/f top §6- §fShows the top factions.\n§6- §f/f transfer (player) §6- §fMakes a new member the leader.\n§6- §f/f allies (ADD|REMOVE|ACCEPT|DENT) §6- §fManage your faction's allies."
HELP_4: "§6- §f/f chat (GLOBAL|FACTION|ALLIANCE) §6- §fChange your chatting configuration.\n§6- §f/f bank (DEPOSIT | WITHDRAW | STATUS) §6- §fManage your faction's bank"
HELP_5: "§6- "
FACTION_CREATE_BROADCAST: "{prefix} §6% §fhas created the faction §6%§f !"
CREATE_USAGE: "{prefix} §cYou must do /f create (name) for create a faction !"
INVALID_NAME: "{prefix} §cThis name is invalid !"
FACTION_ALREADY_EXIST: "{prefix} §cA faction with the same name already exist !"
FACTION_NAME_TOO_SHORT: "{prefix} §cThis faction name is too short !"
FACTION_NAME_TOO_LONG: "{prefix} §cThis faction name is too long !"
SUCCESSFULL_CREATED: "{prefix} §aYou have successfully created the faction % !"
MUST_BE_IN_FACTION: "{prefix} §cYou must be in a faction for do that !"
ALREADY_IN_FACTION: "{prefix} §cYou have already a faction. Do /f del or /f leave for disband or leave your faction !"
FACTION_DISBAND_BROADCAST: "{prefix} §6% §fhas disband the faction §6%§f !"
ONLY_LEADER: "{prefix} §cOnly leader can do that"
ONLY_LEADER_OR_OFFICER: "{prefix} §cOnly leader or officers can do that !"
SUCCESSFULL_DISBAND: "{prefix} §aYou have successfully disband the faction % !"
FACTION_NOT_EXIST: "{prefix} §cThis faction doesn't exist !"
FACTION_INFO_HEADER: "§6- §fInformations of the faction §6% -"
FACTON_INFO_CONTENT: "\n§6Name: §f{faction}\n§6Power: §f{power}\n§6Bank: §f{bank}$\n§6Players: §f{memberscount}\n\n§6Leader: §f{leader}\n§6Officers: §f{officers}\n§6Members: §f{members}\n§6Allies: §f{allies}"
HOME_TELEPORTED: "{prefix} §aYou have been teleported to your faction home"
NOT_HAVE_HOME: "{prefix} §cYour faction doesn't have any home !"
ALREADY_HAVE_HOME: "{prefix} §cYour faction already have a home !"
NOT_FACTION_WORLD: "{prefix} §cYou are not in a faction world !"
HOME_SET: "{prefix} §aYou have successfully created your home !"
HOME_DELETE: "{prefix} §aYou have successfully deleted your home !"
CLAIM_SUCCESS: "{prefix} §aYou have successfully claim this chunk !"
NOT_ENOUGHT_POWER: "{prefix} §cYour faction doesn't have enought power, you need §6% §cpower for claim a new chunk."
ALREADY_CLAIMED: "{prefix} §cThis claim is already claimed by the faction §6% §c!"
MAX_CLAIM: "{prefix} §cYou have reached the claim limit !"
NOT_CLAIM_BY_YOUR_FACTION: "{prefix} §cThis chunk is not claimed by your faction !"
UNCLAIM_SUCCESS: "{prefix} §aYou have successfully unclaim this chunk !"
LEAVE_SUCCESS: "{prefix} §aYou have successfully leave your faction !"
KICK_SUCCESS: "{prefix} §aYou have successfully kicked §6% §ffrom your faction !"
PLAYER_NOT_IN_YOUR_FACTION: "{prefix} §cThat player is not in your faction !"
CANNOT_KICK_PLAYER: "{prefix} §cThis player has a rank higher than or equal than yours !"
KICK_USAGE: "{prefix} §cPlease use: /f kick (name)"
LEADER_CANNOT_LEAVE: "{prefix} §cYou must delete your faction or transfer your leader rank before doing this"
PROMOTE_SUCCESS: "{prefix} §aYou have successfully promoted §6% §ffrom your faction !"
DEMOTE_SUCCESS: "{prefix} §aYou have successfully demoted §6% §ffrom your faction !"
PROMOTE_USAGE: "{prefix} §cPlease use: /f promote (name)"
DEMOTE_USAGE: "{prefix} §cPlease use: /f demote (name)"
PLAYER_ALREADY_MEMBER: "{prefix} §cThis player is already member !"
PLAYER_ALREADY_OFFICER: "{prefix} §cThis player is already officer !"
INVITE_USAGE: "{prefix} §cPlease use: /f invite (name)"
INVITE_SUCCESS: "{prefix} §aYou have successfully invited §6% §aon your faction !"
INVITE_SUCCESS_TARGET: "{prefix} §aYou have been invited to the faction §6% §a!"
PLAYER_NOT_ONLINE: "{prefix} §cThis player is not online !"
PLAYER_ALREADY_IN_FACTION: "{prefix} §cThis player is already in a faction !"
ACCEPT_SUCCESS: "{prefix} §aYou have successfully accept the invitation from the faction §6% §a!"
DENY_SUCCESS: "{prefix} §aYou have successfully deny the invitation from the faction §6% §a!"
JOIN_FACTION_BROADCAST: "{prefix} §6% §ahas joined your faction as a member !"
INVITATION_EXPIRED: "{prefix}§c Your invitation has expired !"
DONT_HAVE_INVITATION: "{prefix} §cYou don't have any invitation !"
FACTION_FULL: "{prefix} §cThis faction has reached the max member count !"
TOP_FACTION_HEADER: "§6- §fTop Faction §6(§f%§6/§f%§6) -"
TOP_FACTION_LINE: "§6#{index} {faction} §fwith §6{power}§f power(s) and §6{members} §fmember(s)"
TRANSFER_USAGE: "{prefix} §cPlease use /f transfer (name) !"
CANNOT_TRANFER_YOURSELF: "{prefix} §cYou can't transfer the faction to yourself !"
TRANSFER_SUCCESS: "{prefix} §aYou have successfully transfered your leader rank to §6% §a!"
ALLIES_USAGE: "{prefix} §cPlease use /f allies (ADD | REMOVE | LIST | ACCEPT | DENY)"
ALLIES_LIST_HEADER: "§6- §fAllies list of your faction §6-"
ALLIES_LIST: "§6List: §f{allies}"
NEW_ALLIANCE_FACTION_BROADCAST: "{prefix} §aYour faction is now allied with % faction"
ALLIES_INVITE_SUCCESS: "{prefix} You have successfully send an alliance request to the % faction !"
ALLIES_INVITE_SUCCESS_TARGET: "{prefix} §aThe faction % want to be in alliance with your faction. Please use /f allies accept or /f allies deny."
DONT_HAVE_ALLIES_REQUEST: "{prefix} §cYour faction doesn't have any allies request !"
ALLIES_REQUEST_EXPIRE: "{prefix} §cYour allies request has expired !"
YOUR_FACTION_MAX_ALLIES: "{prefix} §cYour faction has reached the max allies count"
FACTION_MAX_ALLIES: "{prefix} §cThe faction % has reached the max allies count"
ALLIES_ADD_USAGE: "{prefix} §cPlease use /f allies add (faction)"
ALLIES_REMOVE_USAGE: "{prefix} §cPlease use /f allies remove (faction)"
NOT_ALLIES: "{prefix} §cYour faction is not allied with % faction"
ALLIES_REMOVE_SUCCESS: "{prefix} §cYour faction is no longer allied with the faction %"
ALLIES_DENY_SUCCESS: "{prefix} §aYou have successfully deny the allies request from the faction §6% §a!"
FACTION_SAY: "§6§l(FACTION)§r §6[§f{faction}§6][§f{rank}§6] §f{player} §6: §f{message}"
ALLY_SAY: "§6§l(ALLIANCE)§r §6[§f{faction}§6][§f{rank}§6] §f{player} §6: §f{message}"
CHAT_USAGE: "{prefix} §cPlease use: /f chat (GLOBAL | FACTION | ALLIANCE)"
CHAT_SUCCESS: "{prefix} You have successfully turned your chat on the % mode !"
ALREADY_THIS_CHAT: "{prefix} §cYou are already on the % chat !"
ADMIN_USAGE: "{prefix} §cPlease use /f admin (ADDPOWER | REMOVEPOWER| SETPOWER | DELETE | RENAME | UNCLAIM)"
ADMIN_NOT_IN_CLAIM: "{prefix} §cError, you are not in a claim !"
ADMIN_ADDPOWER_USAGE: "{prefix} §cPlease use /f admin addpower (faction) (amount)"
ADMIN_REMOVEPOWER_USAGE: "{prefix} §cPlease use /f admin removepower (faction) (amount)"
ADMIN_SETPOWER_USAGE: "{prefix} §cPlease use /f admin setpower (faction) (amount)"
ADMIN_DELETE_USAGE: "{prefix} §cPlease use /f admin delete (faction)"
ADMIN_RENAME_USAGE: "{prefix} §cPlease use /f admin rename (faction) (name)"
ENTER_VALID_NUMBER: "{prefix} §cPlease enter a valid number !"
ADMIN_ADDPOWER_SUCCESS: "{prefix} §aYou have successfully add §6% §apowers to this faction !"
ADMIN_REMOVEPOWER_SUCCESS: "{prefix} §aYou have successfully remove §6% §apowers to this faction !"
ADMIN_SETPOWER_SUCCESS: "{prefix} §aYou have successfully set the power of this faction to §6% §a!"
ADMIN_DELETE_SUCCESS: "{prefix} §aYou have successfully delete this faction !"
ADMIN_RENAME_SUCCESS: "{prefix} §aYou have successfully rename this faction to §6% §a!"
ADMIN_UNCLAIM_SUCCESS: "{prefix} §aYou have successfully unclaim this chunk !"
BANK_USAGE: "{prefix} §cPlease use /f bank (DEPOSIT | WITHDRAW | STATUS)"
BANK_STATUS: "{prefix} §aYour faction's bank has §f%§a$ !"
BANK_WITHDRAW_USAGE: "{prefix} §cPlease use /f bank withdraw (amount)"
BANK_DEPOSIT_USAGE: "{prefix} §cPlease use /f bank deposit (amount)"
FACTION_NOT_ENOUGH_MONEY: "{prefix} §cYour faction doesn't have enough money"
NOT_ENOUGH_MONEY: "{prefix} §cYou don't have enough money"
BANK_DEPOST_SUCCESS: "{prefix} §aYou have successfully deposit %$ in your faction's bank"
BANK_WITHDRAW_SUCCESS: "{prefix} §aYou have successfully withdraw %$ from your faction's bank"
