---
#--------------------------------------------------
#SETTINGS CONFIGURATION
#--------------------------------------------------
mysql_address: "45.140.165.82:3306"
mysql_user: "u10613_YhQQRSgzJD"
mysql_password: "gAO6xszMrzWD1+gsz!li@b5."
mysql_db: "s10613_faction"

broadcast_message_created: true
broadcast_message_disband: true

min_faction_name_lenght: 3
max_faction_name_lenght: 16

power_gain_per_kill: 1
power_lost_per_death: 1


#--------------------------------------------------
# LANGUAGE CONFIGURATION
#--------------------------------------------------
Prefix: "§6[§fSimpleFaction§6]§f"
HELP_HEADER: "§6- §fFaction help page §6(§f%§6/§f%§6) §6-"
HELP_1: "§6- §f/f create §6- §fCreate a faction.\n§6- §f/f del §6- §fDisband your faction.\n§6- §f/f info §6- §fShow the information of your or of an another faction."
HELP_2: "§6- "
HELP_3: "§6- "
HELP_4: "§6- "
HELP_5: "§6- "
FACTION_CREATE_BROADCAST: "{prefix} §6% §fhas created the faction §6%§f !"
CREATE_USAGE: "{prefix} §cYou must do /f create (name) for create a faction !"
INVALID_NAME: "{prefix} §cThis name is invalid !"
FACTION_ALREADY_EXIST: "{prefix} §cA faction with the same name already exist !"
FACTION_NAME_TOO_SHORT: "{prefix} §cThis faction name is too short !"
FACTION_NAME_TOO_LONG: "{prefix} §cThis faction name is too long !"
SUCESSFULL_CREATED: "{prefix} §aYou have sucessfull created the faction % !"
MUST_BE_IN_FACTION: "{prefix} §cYou must be in a faction for do that !"
ALREADY_IN_FACTION: "{prefix} §cYou have already a faction. Do /f del or /f leave for disband or leave your faction !"
FACTION_DISBAND_BROADCAST: "{prefix} §6% §fhas disband the faction §6%§f !"
ONLY_LEADER: "{prefix} §cOnly leader can do that"
SUCESSFULL_DISBAND: "{prefix} §aYou have sucessfull disband the faction % !"
FACTION_NOT_EXIST: "{prefix} §cThis faction doesn't exist !"
FACTION_INFO_HEADER: "§6- §fInformations of the faction §6% -"
FACTON_INFO_CONTENT: "\n§6Name: §f{faction}\n§6Power: §f{power}\n§6Players: §f{memberscount}\n\n§6Leader: §f{leader}\n§6Officers: §f{officers}\n§6Members: §f{members} "