---
#--------------------------------------------------
#SETTINGS CONFIGURATION
#--------------------------------------------------
mysql_address: "SERVER ADDRESS"
mysql_user: "USER"
mysql_password: "YOUR PASSWORD"
mysql_db: "YOUR DB"

broadcast_message_created: true
broadcast_message_disband: true

min_faction_name_lenght: 3
max_faction_name_lenght: 16

power_gain_per_kill: 1
power_lost_per_death: 1

faction_worlds: ["world"]

# USAGE: "- POWER NEEDED"
claims:
  - 100
  - 500
  - 800
  - 1000
  - 2500
  - 5000

#--------------------------------------------------
# LANGUAGE CONFIGURATION
#--------------------------------------------------
Prefix: "§6[§fSimpleFaction§6]§f"
PLAYER_ONLY: "{prefix} §cThis command can't be used in the console !"
COMMAND_USAGE: "{prefix} §cThis command does not exist. Use /f help for more command informations !"
HELP_HEADER: "§6- §fFaction help page §6(§f%§6/§f%§6) §6-"
HELP_1: "§6- §f/f create §6- §fCreate a faction.\n§6- §f/f del §6- §fDelete your faction.\n§6- §f/f info §6- §fGet information on a faction.\n§6- §f/f sethome §6- §fSets your faction home.\n§6- §f/f delhome §6- §fDestroys your faction's house."
HELP_2: "§6- §f/f home §6- §fQuick way to get to your faction's home."
HELP_3: "§6- "
HELP_4: "§6- "
HELP_5: "§6- "
FACTION_CREATE_BROADCAST: "{prefix} §6% §fhas created the faction §6%§f !"
CREATE_USAGE: "{prefix} §cYou must do /f create (name) for create a faction !"
INVALID_NAME: "{prefix} §cThis name is invalid !"
FACTION_ALREADY_EXIST: "{prefix} §cA faction with the same name already exist !"
FACTION_NAME_TOO_SHORT: "{prefix} §cThis faction name is too short !"
FACTION_NAME_TOO_LONG: "{prefix} §cThis faction name is too long !"
SUCESSFULL_CREATED: "{prefix} §aYou have sucessfull created the faction % !"
MUST_BE_IN_FACTION: "{prefix} §cYou must be in a faction for do that !"
ALREADY_IN_FACTION: "{prefix} §cYou have already a faction. Do /f del or /f leave for disband or leave your faction !"
FACTION_DISBAND_BROADCAST: "{prefix} §6% §fhas disband the faction §6%§f !"
ONLY_LEADER: "{prefix} §cOnly leader can do that"
ONLY_LEADER_OR_OFFICER: "{prefix} §cOnly leader or officers can do that !"
SUCESSFULL_DISBAND: "{prefix} §aYou have sucessfull disband the faction % !"
FACTION_NOT_EXIST: "{prefix} §cThis faction doesn't exist !"
FACTION_INFO_HEADER: "§6- §fInformations of the faction §6% -"
FACTON_INFO_CONTENT: "\n§6Name: §f{faction}\n§6Power: §f{power}\n§6Players: §f{memberscount}\n\n§6Leader: §f{leader}\n§6Officers: §f{officers}\n§6Members: §f{members}"
HOME_TELEPORTED: "{prefix} §aYou have been teleported to your faction home"
NOT_HAVE_HOME: "{prefix} §cYour faction doesn't have any home !"
ALREADY_HAVE_HOME: "{prefix} §cYour faction already have a home !"
NOT_FACTION_WORLD: "{prefix} §cYou are not in a faction world !"
HOME_SET: "{prefix} §aYou have successfully created your home !"
HOME_DELETE: "{prefix} §aYou have successfully deleted your home !"
CLAIM_SUCESS: "{prefix} §aYou have successfully claim this chunk !"
NOT_ENOUGHT_POWER: "{prefix} §cYour faction doesn't have enought power, you need §6% §cpower for claim a new chunk."
ALREADY_CLAIMED: "{prefix} §cThis claim is already claimed by the faction §6% §c!"
MAX_CLAIM: "{prefix} §cYou have reached the claim limit !"
NOT_CLAIM_BY_YOUR_FACTION: "{prefix} §cThis chunk is not claimed by your faction !"
UNCLAIM_SUCESS: "{prefix} §aYou have successfully unclaim this chunk !"
