---
#--------------------------------------------------
#SETTINGS CONFIGURATION
#--------------------------------------------------
mysql_address: "SERVER ADDRESS"
mysql_user: "USER"
mysql_password: "YOUR PASSWORD"
mysql_db: "YOUR DB"

broadcast_message_created: true
broadcast_message_disband: true

min_faction_name_lenght: 3
max_faction_name_lenght: 16

power_gain_per_kill: 1
power_lost_per_death: 1

faction_worlds: ["world"]

# expire in seconds
invitation_expire_time: 30

faction_max_members: 20

# USAGE: "- POWER NEEDED"
claims:
  - 100
  - 500
  - 800
  - 1000
  - 2500
  - 5000

#--------------------------------------------------
# LANGUAGE CONFIGURATION
#--------------------------------------------------
Prefix: "§6[§fSimpleFaction§6]§f"
PLAYER_ONLY: "{prefix} §cThis command can't be used in the console !"
COMMAND_USAGE: "{prefix} §cThis command does not exist. Use /f help for more command informations !"
HELP_HEADER: "§6- §fFaction help page §6(§f%§6/§f%§6) §6-"
HELP_1: "§6- §f/f create (name) §6- §fCreate a faction.\n§6- §f/f del §6- §fDelete your faction.\n§6- §f/f info §6- §fGet information on a faction.\n§6- §f/f sethome §6- §fSets your faction home.\n§6- §f/f delhome §6- §fDestroys your faction's house."
HELP_2: "§6- §f/f home §6- §fQuick way to get to your faction's home.\n§6- §f/f (claim|unclaim) §6- §fClaim or unclaim your base.\n§6- §f/f (promote|demote) (player) §6- §fPromote or demote a player.\n§6- §f/f leave §6- §fLeave your current faction.\n§6- §f/f kick (player) §6- §fKicks a player from your faction."
HELP_3: "§6- §f/f invite (player) §6- §fInvite a player into your faction.\n§6- §f/f (accept|deny) §6- §fAccept or deny any faction."
HELP_4: "§6- "
HELP_5: "§6- "
FACTION_CREATE_BROADCAST: "{prefix} §6% §fhas created the faction §6%§f !"
CREATE_USAGE: "{prefix} §cYou must do /f create (name) for create a faction !"
INVALID_NAME: "{prefix} §cThis name is invalid !"
FACTION_ALREADY_EXIST: "{prefix} §cA faction with the same name already exist !"
FACTION_NAME_TOO_SHORT: "{prefix} §cThis faction name is too short !"
FACTION_NAME_TOO_LONG: "{prefix} §cThis faction name is too long !"
SUCESSFULL_CREATED: "{prefix} §aYou have sucessfull created the faction % !"
MUST_BE_IN_FACTION: "{prefix} §cYou must be in a faction for do that !"
ALREADY_IN_FACTION: "{prefix} §cYou have already a faction. Do /f del or /f leave for disband or leave your faction !"
FACTION_DISBAND_BROADCAST: "{prefix} §6% §fhas disband the faction §6%§f !"
ONLY_LEADER: "{prefix} §cOnly leader can do that"
ONLY_LEADER_OR_OFFICER: "{prefix} §cOnly leader or officers can do that !"
SUCESSFULL_DISBAND: "{prefix} §aYou have sucessfull disband the faction % !"
FACTION_NOT_EXIST: "{prefix} §cThis faction doesn't exist !"
FACTION_INFO_HEADER: "§6- §fInformations of the faction §6% -"
FACTON_INFO_CONTENT: "\n§6Name: §f{faction}\n§6Power: §f{power}\n§6Players: §f{memberscount}\n\n§6Leader: §f{leader}\n§6Officers: §f{officers}\n§6Members: §f{members}"
HOME_TELEPORTED: "{prefix} §aYou have been teleported to your faction home"
NOT_HAVE_HOME: "{prefix} §cYour faction doesn't have any home !"
ALREADY_HAVE_HOME: "{prefix} §cYour faction already have a home !"
NOT_FACTION_WORLD: "{prefix} §cYou are not in a faction world !"
HOME_SET: "{prefix} §aYou have successfully created your home !"
HOME_DELETE: "{prefix} §aYou have successfully deleted your home !"
CLAIM_SUCESS: "{prefix} §aYou have successfully claim this chunk !"
NOT_ENOUGHT_POWER: "{prefix} §cYour faction doesn't have enought power, you need §6% §cpower for claim a new chunk."
ALREADY_CLAIMED: "{prefix} §cThis claim is already claimed by the faction §6% §c!"
MAX_CLAIM: "{prefix} §cYou have reached the claim limit !"
NOT_CLAIM_BY_YOUR_FACTION: "{prefix} §cThis chunk is not claimed by your faction !"
UNCLAIM_SUCESS: "{prefix} §aYou have successfully unclaim this chunk !"
LEAVE_SUCESS: "{prefix} §aYou have successfully leave your faction !"
KICK_SUCESS: "{prefix} §aYou have successfully kicked §6% §ffrom your faction !"
PLAYER_NOT_IN_YOUR_FACTION: "{prefix} §cThat player is not in your faction !"
CANNOT_KICK_PLAYER: "{prefix} §cThis player has a rank higher than or equal than yours !"
KICK_USAGE: "{prefix} §cPlease use: /f kick (name)"
LEADER_CANNOT_LEAVE: "{prefix} §cYou must delete your faction or transfer your leader rank before doing this"
PROMOTE_SUCESS: "{prefix} §aYou have successfully promoted §6% §ffrom your faction !"
DEMOTE_SUCESS: "{prefix} §aYou have successfully demoted §6% §ffrom your faction !"
PROMOTE_USAGE: "{prefix} §cPlease use: /f promote (name)"
DEMOTE_USAGE: "{prefix} §cPlease use: /f demote (name)"
PLAYER_ALREADY_MEMBER: "{prefix} §cThis player is already member !"
PLAYER_ALREADY_OFFICER: "{prefix} §cThis player is already officer !"
INVITE_USAGE: "{prefix} §cPlease use: /f invite (name)"
INVITE_SUCESS: "{prefix} §aYou have successfully invited §6% §aon your faction !"
INVITE_SUCESS_TARGET: "{prefix} §aYou have been invited to the faction §6% §a!"
PLAYER_NOT_ONLINE: "{prefix} §cThis player is not online !"
PLAYER_ALREADY_IN_FACTION: "{prefix} §cThis player is already in a faction !"
ACCEPT_SUCESS: "{prefix} §aYou have successfully accept the invitation from the faction §6% §a!"
DENY_SUCESS: "{prefix} §aYou have successfully deny the invitation from the faction §6% §a!"
JOIN_FACTION_BROADCAST: "{prefix} §6% §ahas joined your faction as a member !"
INVITATION_EXPIRED: "{prefix}§c Your invitation has expired !"
DONT_HAVE_INVITATION: "{prefix} §cYou don't have any invitation !"
FACTION_FULL: "{prefix} §cThis faction has reached the max member count !"
